apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadmeapp
  namespace: demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      tolerations:
      - key: "capstone"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      containers:
      - name: loadmeapp
        image: 136954245697.dkr.ecr.us-east-1.amazonaws.com/capstone
        ports:
        - containerPort: 80


